config/routes.rb
Rails.application.routes.draw do
  root 'books#index'

  resources :books

  resources :authors

  resources :categories

  resources :publishers

  get 'about' => 'about#index'

  get 'publishers/new'

  get 'publishers/create'

  get 'publishers/update'

  get 'publishers/edit'

  get 'publishers/destroy'

  get 'publishers/index'

  get 'publishers/show'

  get 'authors/new'

  get 'authors/create'

  get 'authors/update'

  get 'authors/edit'

  get 'authors/destroy'

  get 'authors/index'

  get 'authors/show'

  get 'categories/new'

  get 'categories/create'

  get 'categories/update'

  get 'categories/edit'

  get 'categories/destroy'

  get 'categories/index'

  get 'categories/show'

  get 'books/new'

  get 'books/create'

  get 'books/update'

  get 'books/edit'

  get 'books/destroy'

  get 'books/show'

  get 'about/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books

  validates :first_name, presence: true, length: { in: 4..20 }
  validates :last_name, presence: true, length: { in: 4..20 }
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  belongs_to :author
  belongs_to :publisher
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books

  validates :name, presence: true, length: { in: 3..10 }
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books

  validates :name, presence: true, length: { in: 3..10 }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @page_title = 'Acerca de nosotros'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def new
    @page_title = 'Agregar autor'
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      flash[:notice] = "Autor agregado"
      redirect_to authors_path
    else
      render 'new'
    end
  end

  def update
    @author = Author.find(params[:id])
    if @author.update(author_params)
      flash[:notice] = "Autor actualizado"
      redirect_to authors_path
    else
      render 'edit'
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def destroy
    @author = Author.find(params[:id])
    if @author.destroy
      flash[:notice] = "Autor removido"
      redirect_to authors_path
    end
  end

  def index
    @authors = Author.all
  end

  private
    def author_params
      params.require(:author).permit(:first_name, :last_name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @page_title = 'Agregar libro'
    @book = Book.new
    @category = Category.new
    @author = Author.new
    @publisher = Publisher.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Libro agregado"
      redirect_to books_path
    else
      render 'new'
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Libro actualizado"
      redirect_to books_path
    else
      render 'edit'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:notice] = "Libro removido"
      redirect_to books_path
    end
  end

  def index
    @books = Book.all
    @categories = Category.all
  end

  def show
    @book = Book.find(params[:id])
    @categories = Category.all
  end

  private
    def book_params
      params.require(:book).permit(:title, :category_id, :author_id, :publisher_id, :isbn, :price,
      :buy, :format, :excerpt, :pages, :year, :coverpath)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @page_title = 'Agregar categoría'
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Categoría agregada"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Categoría actualizado"
      redirect_to books_path
    else
      render 'edit'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      flash[:notice] = "Categoría removida"
      redirect_to categories_path
    end
  end

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @books = @category.books
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def new
    @page_title = 'Agregar editorial'
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(publisher_params)
    if @publisher.save
      flash[:notice] = "Editorial agregada"
      redirect_to publishers_path
    else
      render 'new'
    end
  end

  def update
    @publisher = Publisher.find(params[:id])
    if @publisher.update(publisher_params)
      flash[:notice] = "Editorial actualizada"
      redirect_to publishers_path
    else
      render 'edit'
    end
  end

  def edit
    @publisher = Publisher.find(params[:id])
  end

  def destroy
    @publisher = Publisher.find(params[:id])
    if @publisher.destroy
      flash[:notice] = "Editorial removida"
      redirect_to publishers_path
    end
  end

  def index
    @publishers = Publisher.all
  end

  private
    def publisher_params
      params.require(:publisher).permit(:name)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/about/index.html.erb
<h1><%= @page_title %></h1>

<p>Aquí cosas sobre la librería</p>

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

app/views/authors/edit.html.erb
<h2>Editar autor</h2>

<%= form_for @author do |f| %>
  <% if @author.errors.any? %>
    <% @author.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= f.label :first_name, "Nombre" %><br/>
    <%= f.text_field :first_name, class:'form-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :last_name, "Apellido" %><br/>
    <%= f.text_field :last_name, class:'form-control' %><br/>
  </div>

  <%= f.submit 'Aceptar', class:'btn btn-primary' %>
  <%= link_to 'Cancelar', authors_path, class:'btn btn-default' %>
<% end %>

app/views/authors/index.html.erb
<h2>Autores</h2>
<table class="table table-striped">
  <tr>
    <th>Nombre del autor</th>
    <th>Acciones</th>
  </tr>
  <% @authors.each do |author| %>
    <tr>
      <td><%= author.first_name %> <%= author.last_name %></td>
      <td><%= link_to 'Editar', edit_author_path(author.id) %> | <%= link_to 'Eliminar',
      author_path(author), method: :delete, data: { confirm: 'Estas seguro?' } %></td>
    </tr>
  <% end %>
</table>

app/views/authors/new.html.erb
<h2>Agregar autor</h2>

<%= form_for @author do |f| %>
  <% if @author.errors.any? %>
    <% @author.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= f.label :first_name, "Nombre" %><br/>
    <%= f.text_field :first_name, class:'form-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :last_name, "Apellido" %><br/>
    <%= f.text_field :last_name, class:'form-control' %><br/>
  </div>

  <%= f.submit 'Aceptar', class:'btn btn-primary' %>
  <%= link_to 'Cancelar', authors_path, class:'btn btn-default' %>
<% end %>

app/views/authors/show.html.erb
<h1>Authors#show</h1>
<p>Find me in app/views/authors/show.html.erb</p>

app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h2>Editar libro</h2>

<%= form_for @book do |f| %>
  <div class="form-group">
    <%= f.label :title, "Titulo" %><br/>
    <%= f.text_field :title, class:'form-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :isbn, "ISBN" %><br/>
    <%= f.text_field :isbn, class:'form-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :category, "Categoria" %><br/>
    <%= f.select :category_id, Category.all.collect { |x| [x.name, x.id] },
        { :include_blank => 'Elige uno' }, class:'form-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :author, "Autor" %><br/>
    <%= f.select :author_id, Author.all.collect { |x| [x.first_name + ' ' + x.last_name, x.id] },
        { :include_blank => 'Elige uno' }, class:'form-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :publisher, "Editorial" %><br/>
    <%= f.select :publisher_id, Publisher.all.collect { |x| [x.name, x.id] },
        { :include_blank => 'Elige uno' }, class:'form-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :format, "Formato" %><br/>
    <%= f.text_field :format, class:'form-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :year, "Año" %><br/>
    <%= f.text_field :year, class:'form-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :coverpath, "Enlace de portada" %><br/>
    <%= f.text_field :coverpath, class:'form-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :excerpt, "Extracto" %><br/>
    <%= f.text_area :excerpt, class:'form-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :pages, "Páginas" %><br/>
    <%= f.number_field :pages, class:'form-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :price, "Precio" %><br/>
    <%= f.text_field :price, class:'form-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :buy, "Enlace de compra" %><br/>
    <%= f.text_field :buy, class:'form-control' %><br/>
  </div>

  <%= f.submit 'Aceptar', class:'btn btn-primary' %>
  <%= link_to 'Cancelar', books_path, class:'btn btn-default' %>
<% end %>

app/views/books/index.html.erb
<div id="books-index">
  <% @books.each_slice(4) do |book| %>
    <div class="row">
      <% book.each do |book| %>
        <div class="col-md-3 col-sm-3">
          <h3><%= book.title %></h3>
          <%= image_tag(book.coverpath) %>
          <%= link_to 'Lee más', book_path(book), class:"btn btn-primary" %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/books/new.html.erb
<h2>Agregar un nuevo libro</h2>

<%= form_for @book do |f| %>
  <div class="form-group">
    <%= f.label :title, "Titulo" %><br/>
    <%= f.text_field :title, class:'form-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :isbn, "ISBN" %><br/>
    <%= f.text_field :isbn, class:'form-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :category, "Categoria" %><br/>
    <%= f.select :category_id, Category.all.collect { |x| [x.name, x.id] },
        { :include_blank => 'Elige uno' }, class:'form-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :author, "Autor" %><br/>
    <%= f.select :author_id, Author.all.collect { |x| [x.first_name + ' ' + x.last_name, x.id] },
        { :include_blank => 'Elige uno' }, class:'form-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :publisher, "Editorial" %><br/>
    <%= f.select :publisher_id, Publisher.all.collect { |x| [x.name, x.id] },
        { :include_blank => 'Elige uno' }, class:'form-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :format, "Formato" %><br/>
    <%= f.text_field :format, class:'form-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :year, "Año" %><br/>
    <%= f.text_field :year, class:'form-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :coverpath, "Enlace de portada" %><br/>
    <%= f.text_field :coverpath, class:'form-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :excerpt, "Extracto" %><br/>
    <%= f.text_area :excerpt, class:'form-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :pages, "Páginas" %><br/>
    <%= f.number_field :pages, class:'form-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :price, "Precio" %><br/>
    <%= f.text_field :price, class:'form-control' %><br/>
  </div>

  <div class="form-group">
    <%= f.label :buy, "Enlace de compra" %><br/>
    <%= f.text_field :buy, class:'form-control' %><br/>
  </div>

  <%= f.submit 'Aceptar', class:'btn btn-primary' %>
  <%= link_to 'Cancelar', books_path, class:'btn btn-default' %>
<% end %>

app/views/books/show.html.erb
<div id="books-show">
  <h2><%= @book.title %></h2>
  <div class="books-show-left">
    <%= image_tag(@book.coverpath) %>
  </div>
  <div class="books-show-right">
    <h3>Información:</h3>
    <ul>
      <li><strong>Categoria: </strong><%= @book.category.name %></li>
      <li><strong>Autor: </strong><%= @book.author.first_name %>
      <%= @book.author.last_name %></li>
      <li><strong>Editorial: </strong><%= @book.publisher.name %></li>
      <li><strong>Año: </strong><%= @book.year %></li>
      <li><strong>ISBN: </strong><%= @book.isbn %></li>
      <li><strong>Formato: </strong><%= @book.format %></li>
      <li><strong>Páginas: </strong><%= @book.pages %></li>
    </ul>
    <%= link_to "Compralo por " + @book.price, @book.buy, class:'btn btn-success', target:'_blank' %>
  </div>
  <div class="clearfix"></div>
  <h4>Extracto</h4>
  <p><%= @book.excerpt %></p>
  <h3>Administrar</h3>
  <%= link_to 'Editar', edit_book_path(@book.id) %> | <%= link_to 'Eliminar', book_path(@book),
  method: :delete, data: { confirm: 'Estas seguro?' } %>
</div>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h2>Editar categoría</h2>

<%= form_for @category do |f| %>
  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= f.label :name, "Nombre" %><br/>
    <%= f.text_field :name, class:'form-control' %><br/>
  </div>

  <%= f.submit 'Aceptar', class:'btn btn-primary' %>
  <%= link_to 'Cancelar', categories_path, class:'btn btn-default' %>
<% end %>

app/views/categories/index.html.erb
<h2>Categorias</h2>
<table class="table table-striped">
  <tr>
    <th>Nombre de la categoría</th>
    <th>Acciones</th>
  </tr>
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td><%= link_to 'Editar', edit_category_path(category.id) %> | <%= link_to 'Eliminar',
      category_path(category), method: :delete, data: { confirm: 'Estas seguro?' } %></td>
    </tr>
  <% end %>
</table>

app/views/categories/new.html.erb
<h2>Agregar categoría</h2>

<%= form_for @category do |f| %>
  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= f.label :name, "Nombre" %><br/>
    <%= f.text_field :name, class:'form-control' %><br/>
  </div>

  <%= f.submit 'Aceptar', class:'btn btn-primary' %>
  <%= link_to 'Cancelar', categories_path, class:'btn btn-default' %>
<% end %>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>
<div id="books-index">
  <% @books.each_slice(4) do |book| %>
    <div class="row">
      <% book.each do |book| %>
        <div class="col-md-3 col-sm-3">
          <h3><%= book.title %></h3>
          <%= image_tag(book.coverpath) %>
          <%= link_to 'Lee más', book_path(book), class:"btn btn-primary" %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><%= @page_title ? @page_title : 'Bienvenido' %> | La Librería</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
          data-target=".navbar-collapse">
            <span class="sr-only">gege</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= params[:controller] == 'books' ? 'active' : '' %>"><%= link_to 'Inicio', root_path %></li>
            <li class="<%= params[:controller] == 'about' ? 'active' : '' %>"><%= link_to 'Acerca de', about_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
              aria-haspopup="true" aria-expanded="false">Agregar <span class="caret"></span></a>
              <ul class="dropdown-menu navbar-right">
                <li><%= link_to 'Libro', new_book_path %></li>
                <li><%= link_to 'Categoria', new_category_path %></li>
                <li><%= link_to 'Autor', new_author_path %></li>
                <li><%= link_to 'Editorial', new_publisher_path %></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
              aria-haspopup="true" aria-expanded="false">Administrar <span class="caret"></span></a>
              <ul class="dropdown-menu navbar-right">
                <li><%= link_to 'Categorias', categories_path %></li>
                <li><%= link_to 'Autores', authors_path %></li>
                <li><%= link_to 'Editoriales', publishers_path %></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <header>
      <div class="container">
        <h1>La Librería <small><%= @page_title ? @page_title : 'Bienvenido' %></small></h1>
      </div>
    </header>

    <section>
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <% if flash[:notice] %>
              <div class="alert alert-success">
                <%= flash[:notice] %>
              </div>
            <% end %>
            <% if flash[:alert] %>
              <div class="alert alert-danger">
                <%= flash[:alert] %>
              </div>
            <% end %>
            <%= yield %>
          </div>
          <div class="col-md-4">
            <%= render 'partials/sidebar' %>
          </div>
        </div>
      </div>
    </section>

    <footer>
      <div class="container">
        <p>La librería 2017</p>
      </div>
    </footer>
  </body>
</html>

app/views/partials/_sidebar.html.erb
<% if params[:controller] == 'about' %>
  <div class="well">
    <h3>Información</h3>
    <ul>
      <li>La libreria</li>
      <li>Dirección</li>
      <li>Estado</li>
      <li>Teléfono</li>
      <li>Correlo electrónico</li>
    </ul>
  </div>
<% end %>

<% if params[:controller] == 'books' && params[:action] == 'index' || params[:action] == 'show' %>
  <div class="list-group">
    <% @categories.each do |category| %>
      <%= link_to category.name, category_path(category.id), class:"list-group-item" %>
    <% end %>
  </div>
<% end %>

app/views/publishers/create.html.erb
<h1>Publishers#create</h1>
<p>Find me in app/views/publishers/create.html.erb</p>

app/views/publishers/destroy.html.erb
<h1>Publishers#destroy</h1>
<p>Find me in app/views/publishers/destroy.html.erb</p>

app/views/publishers/edit.html.erb
<h2>Editar editorial</h2>

<%= form_for @publisher do |f| %>
  <% if @publisher.errors.any? %>
    <% @publisher.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= f.label :name, "Nombre" %><br/>
    <%= f.text_field :name, class:'form-control' %><br/>
  </div>

  <%= f.submit 'Aceptar', class:'btn btn-primary' %>
  <%= link_to 'Cancelar', publishers_path, class:'btn btn-default' %>
<% end %>

app/views/publishers/index.html.erb
<h2>Editoriales</h2>
<table class="table table-striped">
  <tr>
    <th>Nombre de la editorial</th>
    <th>Acciones</th>
  </tr>
  <% @publishers.each do |publisher| %>
    <tr>
      <td><%= publisher.name %></td>
      <td><%= link_to 'Editar', edit_publisher_path(publisher.id) %> | <%= link_to 'Eliminar',
      publisher_path(publisher), method: :delete, data: { confirm: 'Estas seguro?' } %></td>
    </tr>
  <% end %>
</table>

app/views/publishers/new.html.erb
<h2>Agregar editorial</h2>

<%= form_for @publisher do |f| %>
  <% if @publisher.errors.any? %>
    <% @publisher.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= f.label :name, "Nombre" %><br/>
    <%= f.text_field :name, class:'form-control' %><br/>
  </div>

  <%= f.submit 'Aceptar', class:'btn btn-primary' %>
  <%= link_to 'Cancelar', publishers_path, class:'btn btn-default' %>
<% end %>

app/views/publishers/show.html.erb
<h1>Publishers#show</h1>
<p>Find me in app/views/publishers/show.html.erb</p>

app/views/publishers/update.html.erb
<h1>Publishers#update</h1>
<p>Find me in app/views/publishers/update.html.erb</p>